name: Deploy True Legacy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
          VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
        run: |
          npm ci
          npm run build

      - name: Rename dist to truelegacy-frontend
        run: mv ./dist ./truelegacy-frontend-new

      - name: Clean Temporary Directory on Linode
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4967
          script: |
            # Remove old temporary directory if it exists
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      - name: Copy Files to Linode
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4967
          source: ./truelegacy-frontend-new/
          target: ~/deploy-temp/

      - name: Deploy on Linode
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4967
          script: |
             echo "Deploying True Legacy frontend..."

             sudo -n rm -rf /var/www/html/truelegacy-frontend-new
             sudo -n  mkdir -p /var/www/html/truelegacy-frontend-new

             sudo -n cp -R ~/deploy-temp/* /var/www/html/truelegacy-frontend-new

             sudo -n chown -R www-data:www-data /var/www/html/truelegacy-frontend-new
             sudo -n  chmod -R 755 /var/www/html/truelegacy-frontend-new

             sudo -n rm -rf ~/deploy-temp

             # Clear nginx cache and restart
             echo "Restarting Nginx..."
             sudo -n rm -rf /var/cache/nginx/*
             sudo -n systemctl reload nginx
             echo "Deployment completed!"
